-- A file the application stored, uploaded or produced by a signature: an object in S3 (bucket + object_key) and
-- what the application knows about it.
CREATE TABLE document (
    -- UUID version 7, generated by the application: it also names the object, which is written first.
    id          uuid        PRIMARY KEY,
    bucket      text        NOT NULL,
    -- yyyy/MM/dd/<id>.<extension>, dated when stored (UTC).
    object_key  text        NOT NULL,
    -- Original name, for display and downloads.
    file_name   text        NOT NULL,
    size_bytes  bigint      NOT NULL CHECK (size_bytes > 0),
    mime_type   text        NOT NULL,
    -- SHA-256 of the content, in lowercase hex; also checked by S3 when the object is written.
    sha256      text        NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    -- The same instant as the timestamp in the id.
    stored_at   timestamptz NOT NULL,
    UNIQUE (bucket, object_key)
);

-- A signature made by the application: the document that was signed (source), the new document it produced (signed)
-- and who signed it. Signing again (co-signing) takes a signed document as the source of the next signature, so a
-- chain of signatures leads back to the uploaded file. The signer's certificate data is kept with each signature, as
-- a record of what signed it.
CREATE TABLE signature (
    -- UUID version 7, generated by the application.
    id                        uuid        PRIMARY KEY,
    source_document_id        uuid        NOT NULL REFERENCES document (id),
    signed_document_id        uuid        NOT NULL UNIQUE REFERENCES document (id),
    format                    text        NOT NULL CHECK (format IN ('PADES', 'CADES')),
    -- PKI Express signature policy, e.g. PadesBasicWithLTV.
    policy                    text        NOT NULL,
    -- As recorded in the signature itself (the PDF's /M entry, the CAdES signing-time attribute).
    signed_at                 timestamptz NOT NULL,
    -- From the signer's certificate: its subject's common name and e-mail, and the ICP-Brasil CPF or CNPJ (digits).
    signer_name               text        NOT NULL,
    signer_email              text,
    signer_cpf                text        CHECK (signer_cpf ~ '^[0-9]{11}$'),
    signer_cnpj               text        CHECK (signer_cnpj ~ '^[0-9]{14}$'),
    -- Common name of the issuing CA.
    certificate_issuer        text        NOT NULL,
    -- Serial number and SHA-256 thumbprint, in lowercase hex.
    certificate_serial_number text        NOT NULL CHECK (certificate_serial_number ~ '^[0-9a-f]+$'),
    certificate_thumbprint    text        NOT NULL CHECK (certificate_thumbprint ~ '^[0-9a-f]{64}$'),
    certificate_not_before    timestamptz NOT NULL,
    certificate_not_after     timestamptz NOT NULL,
    CHECK (source_document_id <> signed_document_id)
);

CREATE INDEX signature_source_document_id ON signature (source_document_id);
