-- Each document is an object in S3 (bucket + object_key); this row is what the application knows about it.
CREATE TABLE document (
    -- UUID version 7, generated by the application: it also names the object, which is written first.
    id          uuid        PRIMARY KEY,
    bucket      text        NOT NULL,
    -- yyyy/MM/dd/<id>.<extension>, dated when stored (UTC).
    object_key  text        NOT NULL,
    -- Original name, for display and downloads.
    file_name   text        NOT NULL,
    size_bytes  bigint      NOT NULL CHECK (size_bytes > 0),
    mime_type   text        NOT NULL,
    -- When the signature that produced this file was made; null for a file uploaded to be signed.
    signed_at   timestamptz,
    UNIQUE (bucket, object_key)
);
